### PR TITLE
Kubernetes backend with clustering support by using IP addresses

### LINKED ISSUE #28: Add a kubernates backend
A kubernates backend should be able to manage volumes as well and that will assist in moving RabbitMQ servers that have persistent queues.

### PR DESCRIPTION
**Pull request by xek**
fixes #28

### CODE REVIEW

**Comment by gmr** [comment]
Neat, looks like we'll need a preview build soon!  Thanks!

**Comment by Stono** [comment]
When is this comign guys :-) Massively need it!

**Comment by Stono** [comment]
So I'm using it from master at the moment, but currently get this, do you know how to resolve it:

```
=INFO REPORT==== 30-Aug-2016::13:34:27 ===
autocluster: Discovered ['rabbit@10.20.2.3']

=ERROR REPORT==== 30-Aug-2016::13:34:27 ===
** System NOT running to use fully qualified hostnames **
** Hostname 10.20.2.3 is illegal **

=ERROR REPORT==== 30-Aug-2016::13:34:27 ===
autocluster: Can not communicate with cluster nodes.
```

**Comment by xek** [comment]
Setup your cluster to use "long names", I'm doing it with:
```
RABBITMQ_USE_LONGNAME=true
RABBITMQ_NODENAME=rabbit@`hostname --ip-address`
```

**Comment by xek** [comment]
You may also need RabbitMQ with this change https://github.com/rabbitmq/rabbitmq-server/pull/892

**Comment by Stono** [comment]
@xek thank you :-) I will give it a go
Thanks for your work with the k8s support too

**Comment by Stono** [comment]
@xek I'm so close!  I've built rabbitmq from source and applied your patch, as well as installed rabbitmq-autocluster from the k8s commit - however, in kubernetes, I'm getting this.  As you can see, autocluster is finding both pods, however it's getting 'cannot communicate with cluster nodes.

```
=INFO REPORT==== 30-Aug-2016::18:46:05 ===
autocluster: Response: [{ok,{{"HTTP/1.1",200,"OK"},
                             [{"date","Tue, 30 Aug 2016 18:46:05 GMT"},
                              {"content-length","823"},
                              {"content-type","application/json"}],
                             "{\"kind\":\"Endpoints\",\"apiVersion\":\"v1\",\"metadata\":{\"name\":\"rabbitmq\",\"namespace\":\"td-integration\",\"selfLink\":\"/api/v1/namespaces/td-integration/endpoints/rabbitmq\",\"uid\":\"1c5745f0-6b09-11e6-8394-42010af000a6\",\"resourceVersion\":\"753469\",\"creationTimestamp\":\"2016-08-25T21:15:55Z\",\"labels\":{\"app\":\"rabbitmq\",\"tier\":\"messaging\"}},\"subsets\":[{\"addresses\":[{\"ip\":\"10.20.2.3\",\"targetRef\":{\"kind\":\"Pod\",\"namespace\":\"td-integration\",\"name\":\"rabbitmq-3767373793-c1n73\",\"uid\":\"fa3a4d15-6ee1-11e6-8394-42010af000a6\",\"resourceVersion\":\"753465\"}},{\"ip\":\"10.20.2.5\",\"targetRef\":{\"kind\":\"Pod\",\"namespace\":\"td-integration\",\"name\":\"rabbitmq-3767373793-z01wb\",\"uid\":\"a50cbfb0-6ee1-11e6-8394-42010af000a6\",\"resourceVersion\":\"753429\"}}],\"ports\":[{\"name\":\"amqp\",\"port\":5672,\"protocol\":\"TCP\"},{\"name\":\"amqp-old\",\"port\":5671,\"protocol\":\"TCP\"}]}]}\n"}}]

=INFO REPORT==== 30-Aug-2016::18:46:05 ===
autocluster: Discovered ['rabbit@10.20.2.5','rabbit@10.20.2.3']

=ERROR REPORT==== 30-Aug-2016::18:46:05 ===
autocluster: Can not communicate with cluster nodes.
```

The docker container is https://github.com/peopledata/td.rabbitmq
And the kubernetes deployment files are in https://github.com/peopledata/td.rabbitmq/tree/master/kubernetes

Would you mind casting an eye over it and seeing if I'm missing something obvious?

**Comment by Stono** [comment]
Interestingly, the the cookie hash is different on both pods?

**Comment by Stono** [comment]
Fixed it!  
I didn't put the erlang cookie in the right place

```

=INFO REPORT==== 30-Aug-2016::19:49:09 ===
Clustering with ['rabbit@10.20.2.3'] as disc node

=INFO REPORT==== 30-Aug-2016::19:49:10 ===
autocluster: Cluster joined.

```

Boom!
Thanks!

**Comment by Stono** [comment]
@xek it's randomly stopped working... https://github.com/aweber/rabbitmq-autocluster/issues/92

**Comment by michaelklishin** [comment]
I don't know if this issue was originally covering TLS connections but #92 uses TLS, so this is not random.

**Comment by Oloremo** [comment]
Folks, im using this commit and run on the old issue: #51 
Can anyone help?

**Comment by michaelklishin** [comment]
@Oloremo `nxdomain` means a hostname cannot be resolved. Please consider not asking questions in multiple issues, in particular those that have nothing to do with the functionality in this pull request.

**Comment by Oloremo** [comment]
@michaelklishin Sorry for that, I wanted to post this issue here(since im using this commit), but I found this old issue which looks like related.

I do understand what is nxdomain is, and I did provide a proof what resolving is working in this container for this exact dns record in a way it should(for DNS discovery)

**Pull request merged**
