### PR TITLE
DO NOT MERGE Change JSON module 

### PR DESCRIPTION
**Pull request by Gsantomaggio**
Fixes: https://github.com/aweber/rabbitmq-autocluster/issues/120
Modify all the calls that use the `rabbit_json module`.
Add` try_decode_json` in `autocluster_util`.
Fix all the unit tests to use the new JSON module. 
I tested the PR only using ETCD2

This PR requires https://github.com/rabbitmq/rabbitmq-common/pull/165 

Do not merge for 2 reasons:
1- It is not compatible with RabbitMQ versions < 3.7.0
2 - there are still a couple of things that I'd like to modify

In the meanwhile what do you think?
@gmr @michaelklishin

### CODE REVIEW

**Comment by michaelklishin** [comment]
@gmr do you have any objections to merging this?

**Comment by michaelklishin** [comment]
@Gsantomaggio I assume this change is 3.7.x-specific, right? We should create a branch for it as many users will build from master and deploy to 3.6.x.

**Comment by Gsantomaggio** [comment]
@michaelklishin yes, this is form `3.7.x`. 

Yes, I was thinking the same, we should have two branches for `3.6.x` and `3.7.x`

What about following the same RabbitMQ policy ? `master` and `stable` ? In this way it is standard also for the future.

**Comment by Gsantomaggio** [comment]
Merged here: https://github.com/rabbitmq/rabbitmq-autocluster/pull/1

**Comment by gmr** [comment]
This plugin was forked by the RabbitMQ team and is now part of RabbitMQ. More information can be found @ https://github.com/rabbitmq/rabbitmq-autocluster

**Pull request closed without merging**
