### PR TITLE
Tests for #71

### PR DESCRIPTION
**Pull request by binarin**
Tests for #71 and #72

### CODE REVIEW

**Comment by binarin** [comment]
There is some problem with travis config - it actually tests `master` branch. Because my new tests are broken when called via `rebar3`, they only worked through `make test`. Why is `reba3` used for tests? Only for code-coverage or there are some other reasons?

**Comment by gmr** [comment]
Because when you use ``make test`` it makes a bunch of stuff related to rabbitmq that slows down the testing process. The plugin generally doesn't need to do any of the rabbitmq related tests and ``rebar3 eunit`` ends up being faster. I'll check out what issues you're running into and see if it's fixable or if we should abandon the bypass of the rabbitmq server build/etc.

**Comment by gmr** [comment]
Oh and branch picking in ``make test`` for RabbitMQ plugins is a bit wonky IIRC. It requires a ``Makefile`` setting.

**Comment by gmr** [comment]
Another reason for the rebar3 tests was its eunit coverage artifacts are produced in a way that works with the codecov integration that I couldn't get working with ``make test``

**Comment by binarin** [comment]
Yeah, I've fiddled a bit with coverage and branch picking in Makefile, looks like it's not worth it :disappointed: I'll try to make my tests `rebar3`-runnable.

**Comment by binarin** [comment]
So I tinkered a bit with test, and also fixed a bug in my previous PR during that time =)

Some explanation about changes made to testing procedures:
- Get rid of sudo requirment in travis - sudo-less tests starts faster on travis
- Stopped using erlang infrastructure of travis ci - because it's rebar2 based
- Coverage report now are generated using rebar3 plugin
- Proper commit is now tested by Travis run for PR - before that PR commit was completely ignored, and `master` was checked instead.
- Look like `meck` can't mock modules that are absent from the system - so rabbit Makefile is used to fetch `rabbit` app itself and then this fetched apps are injected into tests using `ERL_LIBS`.
- Tests are now runnable both with `rebar3 eunit` and `make tests`.

**Comment by binarin** [comment]
And +8% of coverage =)

**Comment by gmr** [comment]
Awesome, thanks!

**Pull request merged**
